from . import supplier
from . import supplier_category
from . import supplier_article
from . import supplier_contract
from . import contract_clause
from . import supplier_evaluation
from . import evaluation_criteria
from . import evaluation_note
from . import e_gestock_purchase_order_supplier